version: '3'

tasks:
  help:
    cmds:
      - go-task -a
    silent: true
    desc: "Show this pages"

  default:
    - task: help

  build:
    preconditions:
      - sh: '{{if eq OS "windows"}} powershell.exe -Command Test-Path dist {{else}} test ! -d dist {{end}}'
        msg: "Nothing to be done."
    cmds:
      - meson setup build --prefix=$(pwd)
      - ninja -C build install
    silent: true
    desc: "Build the project in release build"

  build-strip:
    preconditions:
      - sh: '{{if eq OS "windows"}} powershell.exe -Command Test-Path dist {{else}} test ! -d dist {{end}}'
        msg: "Nothing to be done."
    cmds:
      - meson setup build --strip --prefix=$(pwd)
      - ninja -C build install
    silent: true
    desc: "Build the project in release build in stripped mode"

  build-dev:
    preconditions:
      - sh: '{{if eq OS "windows"}} powershell.exe -Command Test-Path dist {{else}} test ! -d dist {{end}}'
        msg: "Nothing to be done."
    cmds:
      - meson setup build --buildtype=debugoptmized --prefix=$(pwd)
      - ninja -C build install
    silent: true
    desc: "Build the project in dev build"

  cross-build:
    preconditions:
      - sh: '{{if eq OS "windows"}} powershell.exe -Command Test-Path dist {{else}} test ! -d dist {{end}}'
        msg: "Nothing to be done."
    cmds:
      - meson setup --cross {{.CLI_ARGS}} build --prefix=$(pwd)
      - ninja -C build install
    silent: true
    desc: "Build the project with the compiler of your choice in release mode"

  cross-build-dev:
    preconditions:
      - sh: '{{if eq OS "windows"}} powershell.exe -Command Test-Path dist {{else}} test ! -d dist {{end}}'
        msg: "Nothing to be done."
    cmds:
      - meson setup --cross {{.CLI_ARGS}} build --buildtype=debugoptimized --prefix=$(pwd)
      - ninja -C build install
    silent: true
    desc: "Build the project with the compiler of your choice in dev mode"

  re:
    cmds:
      - meson setup build --reconfigure --prefix=$(pwd)
      - ninja -C build install
    silent: true
    desc: "Re build the project"

  re-dev:
    cmds:
      - meson setup build --reconfigure --buildtype=debugoptimized --prefix=$(pwd)
      - ninja -C build install
    silent: true
    desc: "Re build the project in dev mode"

  re-strip:
    cmds:
      - meson setup build --reconfigure --strip --prefix=$(pwd)
      - ninja -C build install
    silent: true
    desc: "Re build the project with strip"

  build-tests:
    cmds:
      - meson setup build --reconfigure -Dbuild_tests=true --prefix=$(pwd)
      - ninja -C build
    silent: true
    desc: "Build tests files"

  run-tests:
    preconditions:
      - sh: '{{if eq OS "windows" }} powershell.exe -Command Test-Path build {{else}} test -d build {{end}}'
        msg: "Build directory not exist please run build_tests before"
    cmds:
      - meson test -C build
    silent: true
    desc: "Run tests files"

  run-tests-valgrind:
    platforms: ["linux"]
    preconditions:
      - sh: 'test -d build && test -f /usr/bin/valgrind'
        msg: "Build directory not exist please run build_tests before or valgrind is missing !"
    cmds:
      - meson test -C build --verbose --wrapper=valgrind
    silent: true
    desc: "Run tests files with valgrind"

  list-tests:
    preconditions:
      - sh: '{{if eq OS "windows" }} powershell.exe -Command Test-Path build {{else}} test -d build {{end}}'
        msg: "Build directory not exist please run build_tests before"
    cmds:
      - meson test -C build --list
    silent: true
    desc: "List all tests"

  run-test-suite:
    preconditions:
      - sh: '{{if eq OS "windows" }} powershell.exe -Command Test-Path build {{else}} test -d build {{end}}'
        msg: "Build directory not exist please run build_tests before"
    cmds:
      - meson test -C build --verbose {{.CLI_ARGS}}
    silent: true
    desc: "Run specified tests suite"

  run-test-suite-valgrind:
    platforms: ["linux"]
    preconditions:
      - sh: 'test -d build && test -d /usr/bin/valgrind'
        msg: "Build directory not exist please run build_tests before"
    cmds:
      - meson test -C build --verbose --wrapper=valgrind {{.CLI_ARGS}}
    silent: true
    desc: "Run specified tests suite with valgrind"


  install:
    platforms: ["linux"]
    preconditions:
      - test -d dist
    cmds:
      - sudo cp ./dist/shared/*.so ./dist/static/*.a /usr/lib/
      - sudo mkdir -p /usr/include/etheria/
      - sudo cp ./inc/eth-std.h /usr/include/etheria/
      - echo -e "[\033[32m+\033[00m] Installed successfully at \033[32m$(ls /usr/lib/ | grep libetheria)\033[00m !"
    silent: true
    desc: "Install library on the system"
    prompt: "Do you want install in (/usr/lib/)"

  rm_install:
    platforms: ["linux"]
    preconditions:
      - test -f /usr/lib/libetheria-std.a
      - test -f /usr/lib/libetheria-std.so
      - test -d /usr/include/etheria/
    cmds:
      - sudo rm -rf /usr/lib/libetheria-std.a /usr/lib/libetheria-std.so /usr/include/etheria/
      - echo -e "[\033[32m+\033[00m] Removed successfully !"
    silent: true
    desc: "Remove installed etheria Standard library on the system"
    prompt: "Do you want remove etheria-std library"

  clean:
    cmds:
      - '{{if eq OS "windows" }} cmd.exe /c rmdir build /S /Q {{else}} rm -rf build {{end}}'
      - '{{if eq OS "windows" }} cmd.exe /c echo clean build directory removed {{else}} echo -e "[\033[32m+\033[00m] clean \033[32mbuild\033[00m directory removed \033[32msuccessully\033[00m !" {{end}}'
    silent: true
    desc: "Clean build directory"

  fclean:
      deps:
        - clean
      cmds:
        - cmd: '{{if eq OS "windows"}} cmd.exe /c rmdir dist /S /Q {{else}} rm -rf dist {{end}}'
          ignore_error: true
        - '{{if eq OS "windows"}} cmd.exe /c echo clean dist directory removed ! {{else}} echo -e "[\033[32m+\033[00m] clean \033[32mdist\033[00m directory removed \033[32msuccessully\033[00m !"{{end}}'
      silent: true
      desc: "Full clean remove build directory and dist directory"
