version: '3'

tasks:
  help:
    cmds:
      - go-task -a
    silent: true
    desc: "Show this pages"

  default:
    - task: help

  build:
    preconditions:
      - sh: '{{if eq OS "windows"}} cmd.exe /c "WINDOWS" else "test ! -d dist"'
        msg: "Nothing to be done."
    cmds:
      - meson setup build --buildtype=release --prefix=$(pwd)
      - ninja -C build install
    silent: true
    desc: "Build the project"

  re:
    cmds:
      - meson setup build --reconfigure --buildtype=release --prefix=$(pwd)
      - ninja -C build install
    silent: true
    desc: "Re build the project"

  tests:
    cmds:
      - meson setup build --reconfigure -Dbuild_tests=true --buildtype=release --prefix=$(pwd)
      - ninja -C build install
    silent: true
    desc: "Build tests files"

  install:
    preconditions:
      - test -d dist
    cmds:
      - sudo cp ./dist/shared/*.so ./dist/static/*.a /usr/lib/
      - sudo mkdir -p /usr/include/etheria/
      - sudo cp ./inc/eth-std.h /usr/include/etheria/
      - echo -e "[\033[32m+\033[00m] Installed successfully at \033[32m$(ls /usr/lib/ | grep libetheria)\033[00m !"
    silent: true
    desc: "Install library on the system"
    prompt: "Do you want install in (/usr/lib/)"

  rm_install:
    preconditions:
      - test -f /usr/lib/libetheria-std.a
      - test -f /usr/lib/libetheria-std.so
      - test -d /usr/include/etheria/
    cmds:
      - sudo rm -rf /usr/lib/libetheria-std.a /usr/lib/libetheria-std.so /usr/include/etheria/
      - echo -e "[\033[32m+\033[00m] Removed successfully !"
    silent: true
    desc: "Remove installed etheria Standard library on the system"
    prompt: "Do you want remove etheria-std library"

  clean-test:
    cmds:
      - rm -rf ./tests/output/
    silent: true
    desc: "Clean tests output directory"

  clean:
    cmds:
      - rm -rf build
      - echo -e "[\033[32m+\033[00m] clean \033[32mbuild\033[00m directory removed \033[32msuccessully\033[00m !"
    silent: true
    desc: "Clean build directory"

  fclean:
      deps:
        - clean
      cmds:
        - rm -rf dist
        - echo -e "[\033[32m+\033[00m] clean \033[32mdist\033[00m directory removed \033[32msuccessully\033[00m !"
      silent: true
      desc: "Full clean remove build directory and dist directory"
