name: Ubuntu-Latest GCC - Build Release

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  actions: write
  id-token: write
  attestations: write
  packages: write
  deployments: write

jobs:
  
  build: 
    runs-on: [ubuntu-latest]
    steps: 
      - name: Checkout repository ${{ github.repository }} on a branch ${{ github.ref_name }} triggered by ${{ github.event_name }}
        uses: actions/checkout@v4
      
      - run: "echo the ${{ github.repository }} has been cloned in the container !"

      - name: 🔄 Installing task...
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
      
      - name: 🔄 Installing Meson package build system...
        run: pip install meson

      - name: 🔄 Installing Dependencies...
        run: |
          sudo apt-get update
          echo "📦 Installing libcriterion-dev, Ninja, GCC New Version"
          sudo apt-get install -y libcriterion-dev ninja-build gcc-12
          sudo ln -s -f /usr/bin/gcc-12 /usr/bin/gcc
          echo "✅ Dependencies installed!"

      - name: Run build release task...
        run: |
          echo "🏗️ Setting up Meson build system..."
          task build fclean
          echo "🎉 Build completed with Meson!"
    
  deployments:
    runs-on: [ubuntu-latest]
    needs: build
    steps:
      - name: Checkout repository ${{ github.repository }} on a branch ${{ github.ref_name }} triggered by ${{ github.event_name }}
        uses: actions/checkout@v4
      
      - run: "echo the ${{ github.repository }} has been cloned in the container !"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: etheria-std
          path: .
